module.exports = {
  premier_league: [
    { team_name: "Arsenal", search_name: 'Arsenal', league: "England Premier League", friendly_name: "arsenal", url: "https://corner-stats.com/arsenal/england/team/8", id: '1079'},
    { team_name: "Bournemouth", search_name: 'Bournemouth', league: "England Premier League", friendly_name: "bournemouth", url: "https://corner-stats.com/bournemouth/england/team/1682", id: '398'},
    { team_name: "Brighton", search_name: 'Brighton', league: "England Premier League", friendly_name: "brighton", url: "https://corner-stats.com/brighton/england/team/1499", id: '556' },
    { team_name: "Burnley", search_name: 'Burnley', league: "England Premier League", friendly_name: "burnley", url: "https://corner-stats.com/burnley/england/team/1629", id: '497' },
    { team_name: "Chelsea", search_name: 'Chelsea', league: "England Premier League", friendly_name: "chelsea", url: "https://corner-stats.com/chelsea/england/team/1", id: '558' },
    { team_name: "Crystal Palace", search_name: 'Crystal Palace', league: "England Premier League", friendly_name: "crystal_palace", url: "https://corner-stats.com/crystal-palace/england/team/1485", id: '507' },
    { team_name: "Everton", search_name: 'Everton', league: "England Premier League", friendly_name: "everton", url: "https://corner-stats.com/everton/england/team/6", id: '511' },
    { team_name: "Huddersfield", search_name: 'Huddersfield', league: "England Premier League", friendly_name: "huddersfield", url: "https://corner-stats.com/huddersfield/england/team/1666", id: '504' },
    { team_name: "Leicester", search_name: 'Leicester', league: "England Premier League", friendly_name: "leicester", url: "https://corner-stats.com/leicester/england/team/1490", id: '542' },
    { team_name: "Liverpool", search_name: 'Liverpool', league: "England Premier League", friendly_name: "liverpool", url: "https://corner-stats.com/liverpool/england/team/18", id: '1080' },
    { team_name: "Manchester City", search_name: 'Man City', league: "England Premier League", friendly_name: "manchester_city", url: "https://corner-stats.com/man-city/england/team/4", id: '623' },
    { team_name: "Manchester United", search_name: 'Man Utd', league: "England Premier League", friendly_name: "manchester_united", url: "https://corner-stats.com/man-utd/england/team/5", id: '624' },
    { team_name: "Newcastle", search_name: 'Newcastle', league: "England Premier League", friendly_name: "newcastle", url: "https://corner-stats.com/newcastle/england/team/10", id: '1569' },
    { team_name: "Southampton", search_name: 'Southampton', league: "England Premier League", friendly_name: "southampton", url: "https://corner-stats.com/southampton/england/team/20", id: '547' },
    { team_name: "Stoke", search_name: 'Stoke', league: "England Premier League", friendly_name: "stoke", url: "https://corner-stats.com/stoke/england/team/12", id: '1082' },
    { team_name: "Swansea", search_name: 'Swansea', league: "England Premier League", friendly_name: "swansea", url: "https://corner-stats.com/swansea/england/team/2", id: '498' },
    { team_name: "Tottenham", search_name: 'Tottenham', league: "England Premier League", friendly_name: "tottenham", url: "https://corner-stats.com/tottenham/england/team/14", id: '1656' },
    { team_name: "Watford", search_name: 'Watford', league: "England Premier League", friendly_name: "watford", url: "https://corner-stats.com/watford/england/team/1498", id: '530' },
    { team_name: "West Brom", search_name: 'West Brom', league: "England Premier League", friendly_name: "west_brom", url: "https://corner-stats.com/west-brom/england/team/3", id: '557' },
    { team_name: "West Ham", search_name: 'West Ham', league: "England Premier League", friendly_name: "west_ham", url: "https://corner-stats.com/west-ham/england/team/7", id: '559' }
  ],
  efl_championship: [
    { team_name: "Aston Villa", league: "efl_championship", friendly_name: "aston_villa", url: "https://corner-stats.com/aston-villa/england/team/17"},
    { team_name: "Barnsley", league: "efl_championship", friendly_name: "barnsley", url: "https://corner-stats.com/barnsley/england/team/1501"},
    { team_name: "Birmingham City", league: "efl_championship", friendly_name: "birmingham_city", url: "https://corner-stats.com/birmingham/england/team/1486" },
    { team_name: "Bolton Wanderers", league: "efl_championship", friendly_name: "bolton_wanderers", url: "https://corner-stats.com/bolton/england/team/1702" },
    { team_name: "Brenford", league: "efl_championship", friendly_name: "brentford", url: "https://corner-stats.com/brentford/england/team/2015" },
    { team_name: "Bristol City", league: "efl_championship", friendly_name: "bristol_city", url: "https://corner-stats.com/bristol-city/england/team/1504" },
    { team_name: "Burton Albion", league: "efl_championship", friendly_name: "burton_albion", url: "https://corner-stats.com/burton-albion/england/team/1901" },
    { team_name: "Cardiff City", league: "efl_championship", friendly_name: "cardiff_city", url: "https://corner-stats.com/cardiff/wales/team/1488" },
    { team_name: "Derby County", league: "efl_championship", friendly_name: "derby_county", url: "https://corner-stats.com/derby/england/team/1500" },
    { team_name: "Fulham", league: "efl_championship", friendly_name: "fulham", url: "https://corner-stats.com/fulham/england/team/11" },
    { team_name: "Hull City", league: "efl_championship", friendly_name: "hull_city", url: "https://corner-stats.com/hull/england/team/1489" },
    { team_name: "Ipswich Town", league: "efl_championship", friendly_name: "ipswich_town", url: "https://corner-stats.com/ipswich/england/team/1493" },
    { team_name: "Leeds United", league: "efl_championship", friendly_name: "leeds_united", url: "https://corner-stats.com/leeds/england/team/157" },
    { team_name: "Middlesbrough", league: "efl_championship", friendly_name: "middlesbrough", url: "https://corner-stats.com/middlesbrough/england/team/1503" },
    { team_name: "Millwall", league: "efl_championship", friendly_name: "millwall", url: "https://corner-stats.com/millwall/england/team/436" },
    { team_name: "Norwich City", league: "efl_championship", friendly_name: "norwich_city", url: "https://corner-stats.com/norwich/england/team/15" },
    { team_name: "Nottingham Forest", league: "efl_championship", friendly_name: "nottingham_forest", url: "https://corner-stats.com/nottm-forest/england/team/1673" },
    { team_name: "Preston North End", league: "efl_championship", friendly_name: "preston_north_end", url: "https://corner-stats.com/preston/england/team/1855" },
    { team_name: "Queens Park Rangers", league: "efl_championship", friendly_name: "queens_park_rangers", url: "https://corner-stats.com/qpr/england/team/19" },
    { team_name: "Reading", league: "efl_championship", friendly_name: "reading", url: "https://corner-stats.com/reading/england/team/16" },
    { team_name: "Sheffield United", league: "efl_championship", friendly_name: "sheffield_united", url: "https://corner-stats.com/sheff-utd/england/team/1718" },
    { team_name: "Sheffield Wednesday", league: "efl_championship", friendly_name: "sheffield_wednesday", url: "https://corner-stats.com/sheff-wed/england/team/1491" },
    { team_name: "Sunderland", league: "efl_championship", friendly_name: "sunderland", url: "https://corner-stats.com/sunderland/england/team/13" },
    { team_name: "Wolverhampton Wanderers", league: "efl_championship", friendly_name: "wolverhampton_wanderers", url: "https://corner-stats.com/wolverhampton/england/team/1903" }
  ],
  efl_one: [
    { team_name: "AFC Wimbledon", league: "efl_one", friendly_name: "afc_wimbledon", url: "https://corner-stats.com/afc-wimbledon/england/team/1854"},
    { team_name: "Blackburn Rovers", league: "efl_one", friendly_name: "blackburn_rovers", url: "https://corner-stats.com/blackburn/england/team/1642"},
    { team_name: "Blackpool", league: "efl_one", friendly_name: "blackpool", url: "https://corner-stats.com/blackpool/england/team/1654" },
    { team_name: "Bradford City", league: "efl_one", friendly_name: "bradford_city", url: "https://corner-stats.com/bradford/england/team/2188" },
    { team_name: "Bristol Rovers", league: "efl_one", friendly_name: "bristol_rovers", url: "https://corner-stats.com/bristol-rovers/england/team/676" },
    { team_name: "Bury", league: "efl_one", friendly_name: "bury", url: "https://corner-stats.com/bury/england/team/1953" },
    { team_name: "Charlton Athletic", league: "efl_one", friendly_name: "charlton_athletic", url: "https://corner-stats.com/charlton/england/team/1657" },
    { team_name: "Doncaster Rovers", league: "efl_one", friendly_name: "doncaster_rovers", url: "https://corner-stats.com/doncaster/england/team/1637" },
    { team_name: "Fleetwood Town", league: "efl_one", friendly_name: "fleetwood_town", url: "https://corner-stats.com/fleetwood-town/england/team/2007" },
    { team_name: "Gillingham", league: "efl_one", friendly_name: "gillingham", url: "https://corner-stats.com/gillingham/england/team/2088" },
    { team_name: "Milton Keynes Dons", league: "efl_one", friendly_name: "milton_keynes_dons", url: "https://corner-stats.com/milton-keynes-dons/england/team/1721" },
    { team_name: "Northampton Town", league: "efl_one", friendly_name: "northampton_town", url: "https://corner-stats.com/northampton/england/team/2383" },
    { team_name: "Oldham Athletic", league: "efl_one", friendly_name: "oldham_athletic", url: "https://corner-stats.com/oldham/england/team/1720" },
    { team_name: "Oxford United", league: "efl_one", friendly_name: "oxford_united", url: "https://corner-stats.com/oxford-utd/england/team/2087" },
    { team_name: "Peterborough United", league: "efl_one", friendly_name: "peterborough_united", url: "https://corner-stats.com/peterborough/england/team/1496" },
    { team_name: "Plymouth Argyle ", league: "efl_one", friendly_name: "plymouth_argyle", url: "https://corner-stats.com/plymouth/england/team/1951" },
    { team_name: "Portsmouth", league: "efl_one", friendly_name: "portsmouth", url: "https://corner-stats.com/portsmouth/england/team/2089" },
    { team_name: "Rochdale", league: "efl_one", friendly_name: "rochdale", url: "https://corner-stats.com/rochdale/england/team/1993" },
    { team_name: "Rotherham United", league: "efl_one", friendly_name: "rotherham_united", url: "https://corner-stats.com/rotherham/england/team/2086" },
    { team_name: "Scunthorpe United", league: "efl_one", friendly_name: "scunthorpe_united", url: "https://corner-stats.com/scunthorpe/england/team/2090" },
    { team_name: "Shrewsbury Town", league: "efl_one", friendly_name: "shrewsbury_town", url: "https://corner-stats.com/shrewsbury/england/team/1968" },
    { team_name: "Southend United", league: "efl_one", friendly_name: "southend_united", url: "https://corner-stats.com/southend/england/team/1946" },
    { team_name: "Walsall", league: "efl_one", friendly_name: "walsall", url: "https://corner-stats.com/walsall/england/team/1956" },
    { team_name: "Wigan Athletic", league: "efl_one", friendly_name: "wigan_athletic", url: "https://corner-stats.com/wigan/england/team/9" }
  ],
  efl_two: [
    { team_name: "Accrington Stanley", league: "efl_two", friendly_name: "accrington_stanley", url: "https://corner-stats.com/accrington-stanley/england/team/2378"},
    { team_name: "Barnet", league: "efl_two", friendly_name: "barnet", url: "https://corner-stats.com/barnet-fc/england/team/669"},
    { team_name: "Cambridge United", league: "efl_two", friendly_name: "cambridge_united", url: "https://corner-stats.com/cambridge-utd/england/team/2162" },
    { team_name: "Carlisle United", league: "efl_two", friendly_name: "carlisle_united", url: "https://corner-stats.com/carlisle/england/team/1719" },
    { team_name: "Cheltenham Town", league: "efl_two", friendly_name: "cheltenham_town", url: "https://corner-stats.com/cheltenham/england/team/2381" },
    { team_name: "Chesterfield", league: "efl_two", friendly_name: "chesterfield", url: "https://corner-stats.com/chesterfield/england/team/1943" },
    { team_name: "Colchester United", league: "efl_two", friendly_name: "colchester_united", url: "https://corner-stats.com/colchester/england/team/2375" },
    { team_name: "Coventry City", league: "efl_two", friendly_name: "coventry_city", url: "https://corner-stats.com/coventry/england/team/1753" },
    { team_name: "Crawley Town", league: "efl_two", friendly_name: "crawley_town", url: "https://corner-stats.com/crawley-town/england/team/1994" },
    { team_name: "Crewe Alexandra", league: "efl_two", friendly_name: "crewe_alexandra", url: "https://corner-stats.com/crewe/england/team/2377" },
    { team_name: "Exeter City", league: "efl_two", friendly_name: "exeter_city", url: "https://corner-stats.com/exeter/england/team/1952" },
    { team_name: "Forest Green Rovers", league: "efl_two", friendly_name: "forest_green_rovers", url: "https://corner-stats.com/forest-green-r/england/team/3432" },
    { team_name: "Grimsby Town", league: "efl_two", friendly_name: "grimsby_town", url: "https://corner-stats.com/grimsby-town-fc/england/team/3433" },
    { team_name: "Lincoln City", league: "efl_two", friendly_name: "lincoln_city", url: "https://corner-stats.com/lincoln-city-fc/england/team/3864" },
    { team_name: "Luton Town", league: "efl_two", friendly_name: "luton_town", url: "https://corner-stats.com/luton/england/team/2379" },
    { team_name: "Mansfield Town", league: "efl_two", friendly_name: "mansfield_town", url: "https://corner-stats.com/mansfield/england/team/1940" },
    { team_name: "Morecambe", league: "efl_two", friendly_name: "morecambe", url: "https://corner-stats.com/morecambe/england/team/2384" },
    { team_name: "Newport County", league: "efl_two", friendly_name: "newport_county", url: "https://corner-stats.com/newport-county/england/team/1902" },
    { team_name: "Notts County", league: "efl_two", friendly_name: "notts_county", url: "https://corner-stats.com/notts-county/england/team/2376" },
    { team_name: "Port Vale", league: "efl_two", friendly_name: "port_vale", url: "https://corner-stats.com/port-vale/england/team/1955" },
    { team_name: "Stevenage", league: "efl_two", friendly_name: "stevenage", url: "https://corner-stats.com/stevenage/england/team/1752" },
    { team_name: "Swindon Town", league: "efl_two", friendly_name: "swindon_town", url: "https://corner-stats.com/swindon/england/team/1484" },
    { team_name: "Wycombe Wanderers", league: "efl_two", friendly_name: "wycombe_wanderers", url: "https://corner-stats.com/wycombe/england/team/1853" },
    { team_name: "Yeovil Town", league: "efl_two", friendly_name: "yeovil_town", url: "https://corner-stats.com/yeovil/england/team/1502" }
  ],
 serie_a: [
  { team_name: "AC Milan", search_name: 'AC Milan', league: "Italy Serie A", friendly_name: "ac_milan", url: "https://corner-stats.com/ac-milan/italy/team/48", id: '721'},
  { team_name: "Atalanta", search_name: 'Atalanta', league: "Italy Serie A", friendly_name: "atalanta", url: "https://corner-stats.com/atalanta/italy/team/57", id: '453'},
  { team_name: "Benevento", search_name: 'Benevento', league: "Italy Serie A", friendly_name: "benevento", url: "https://corner-stats.com/benevento/italy/team/3740", id: '3720'},
  { team_name: "Bologna", search_name: 'Bologna', league: "Italy Serie A", friendly_name: "bologna", url: "https://corner-stats.com/bologna/italy/team/54", id: '996'},
  { team_name: "Cagliari", search_name: 'Cagliari', league: "Italy Serie A", friendly_name: "cagliari", url: "https://corner-stats.com/cagliari/italy/team/52", id: '1018'},
  { team_name: "Chievo", search_name: 'Chievo', league: "Italy Serie A", friendly_name: "chievo", url: "https://corner-stats.com/chievo/italy/team/50", id: '995'},
  { team_name: "Crotone", search_name: 'Crotone', league: "Italy Serie A", friendly_name: "crotone", url: "https://corner-stats.com/crotone/italy/team/1534", id: '252'},
  { team_name: "Fiorentina", search_name: 'Fiorentina', league: "Italy Serie A", friendly_name: "fiorentina", url: "https://corner-stats.com/fiorentina/italy/team/49", id: '1003'},
  { team_name: "Genoa", search_name: 'Genoa', league: "Italy Serie A", friendly_name: "genoa", url: "https://corner-stats.com/genoa/italy/team/46", id: '1009'},
  { team_name: "Inter Milan", search_name: 'Inter Milan', league: "Italy Serie A", friendly_name: "inter_milan", url: "https://corner-stats.com/inter-milan/italy/team/47", id: '726'},
  { team_name: "Juventus", search_name: 'Juventus', league: "Italy Serie A", friendly_name: "juventus", url: "https://corner-stats.com/juventus/italy/team/39", id: '1004'},
  { team_name: "Lazio", search_name: 'Lazio', league: "Italy Serie A", friendly_name: "lazio", url: "https://corner-stats.com/lazio/italy/team/41", id: '992'},
  { team_name: "Napoli", search_name: 'Napoli', league: "Italy Serie A", friendly_name: "napoli", url: "https://corner-stats.com/napoli/italy/team/40", id: '1211'},
  { team_name: "Roma", search_name: 'Roma', league: "Italy Serie A", friendly_name: "roma", url: "https://corner-stats.com/roma/italy/team/43", id: '619'},
  { team_name: "Sampdoria", search_name: 'Sampdoria', league: "Italy Serie A", friendly_name: "sampdoria", url: "https://corner-stats.com/sampdoria/italy/team/42", id: '722'},
  { team_name: "Sassuolo", search_name: 'Sassuolo', league: "Italy Serie A", friendly_name: "sassuolo", url: "https://corner-stats.com/sassuolo/italy/team/1524", id: '1810'},
  { team_name: "Spal", search_name: 'Spal', league: "Italy Serie A", friendly_name: "spal", url: "https://corner-stats.com/real-societa/italy/team/796", id: '4045'},
  { team_name: "Torino", search_name: 'Torino', league: "Italy Serie A", friendly_name: "torino", url: "https://corner-stats.com/torino/italy/team/45", id: '1453'},
  { team_name: "Udinese", search_name: 'Udinese', league: "Italy Serie A", friendly_name: "udinese", url: "https://corner-stats.com/udinese/italy/team/53", id: '1212'},
  { team_name: "Verona", search_name: 'Verona', league: "Italy Serie A", friendly_name: "verona", url: "https://corner-stats.com/verona/italy/team/1523", id: '3993'}
],
serie_b: [
 { team_name: "Ascoli", league: "serie_b", friendly_name: "ascoli", url: "https://corner-stats.com/ascoli/italy/team/341"},
 { team_name: "Avellino", league: "serie_b", friendly_name: "avellino", url: "https://corner-stats.com/avellino/italy/team/1536"},
 { team_name: "Bari", league: "serie_b", friendly_name: "bari", url: "https://corner-stats.com/bari/italy/team/1532"},
 { team_name: "Brescia", league: "serie_b", friendly_name: "brescia", url: "https://corner-stats.com/brescia/italy/team/1616" },
 { team_name: "Carpi", league: "serie_b", friendly_name: "carpi", url: "https://corner-stats.com/carpi/italy/team/1677" },
 { team_name: "Cesena", league: "serie_b", friendly_name: "cesena", url: "https://corner-stats.com/cesena/italy/team/1530" },
 { team_name: "Cittadella", league: "serie_b", friendly_name: "cittadella", url: "https://corner-stats.com/cittadella/italy/team/1656" },
 { team_name: "Cremonese", league: "serie_b", friendly_name: "cremonese", url: "https://corner-stats.com/us-cremonese/italy/team/2130" },
 { team_name: "Empoli", league: "serie_b", friendly_name: "empoli", url: "https://corner-stats.com/empoli/italy/team/1538" },
 { team_name: "Foggia", league: "serie_b", friendly_name: "foggia", url: "https://corner-stats.com/foggia-calcio/italy/team/798" },
 { team_name: "Frosinone", league: "serie_b", friendly_name: "frosinone", url: "https://corner-stats.com/frosinone/italy/team/2118" },
 { team_name: "Novara", league: "serie_b", friendly_name: "novara", url: "https://corner-stats.com/novara-calcio/italy/team/1674" },
 { team_name: "Palermo", league: "serie_b", friendly_name: "palermo", url: "https://corner-stats.com/palermo/italy/team/55" },
 { team_name: "Parma", league: "serie_b", friendly_name: "parma", url: "https://corner-stats.com/parma/italy/team/51" },
 { team_name: "Perugia", league: "serie_b", friendly_name: "perugia", url: "https://corner-stats.com/perugia/italy/team/2033" },
 { team_name: "Pescara", league: "serie_b", friendly_name: "pescara", url: "https://corner-stats.com/pescara/italy/team/56" },
 { team_name: "Pro Vercelli", league: "serie_b", friendly_name: "pro_vercelli", url: "https://corner-stats.com/pro-vercelli/italy/team/2074" },
 { team_name: "Salernitana", league: "serie_b", friendly_name: "salernitana", url: "https://corner-stats.com/us-salernitana/italy/team/2057" },
 { team_name: "Spezia", league: "serie_b", friendly_name: "spezia", url: "https://corner-stats.com/spezia/italy/team/1531" },
 { team_name: "Ternana", league: "serie_b", friendly_name: "ternana", url: "https://corner-stats.com/verona/italy/team/1523" },
 { team_name: "Venezia", league: "serie_b", friendly_name: "venezia", url: "https://corner-stats.com/unione-venezia/italy/team/3734" },
 { team_name: "Virtus Entella", league: "serie_b", friendly_name: "virtus_entella", url: "https://corner-stats.com/virtus-entella/italy/team/2075" }
],
bundesliga: [
 { team_name: "FC Koln", league: "bundesliga", friendly_name: "fc_koln", url: "https://corner-stats.com/cologne/germany/team/1517"},
 { team_name: "FC Mainz", league: "bundesliga", friendly_name: "fc_mainz", url: "https://corner-stats.com/mainz/germany/team/33"},
 { team_name: "Bayer Leverkusen", league: "bundesliga", friendly_name: "bayer_leverkusen", url: "https://corner-stats.com/bayer-leverkusen/germany/team/29"},
 { team_name: "Borussia Dortmund", league: "bundesliga", friendly_name: "borussia_dortmund", url: "https://corner-stats.com/borussia-dortmund/germany/team/26" },
 { team_name: "Borussia Monchengladbach", league: "bundesliga", friendly_name: "borussia_monchengladbach", url: "https://corner-stats.com/borussia-mgladbach/germany/team/27" },
 { team_name: "Eintracht Frankfurt", league: "bundesliga", friendly_name: "eintracht_frankfurt", url: "https://corner-stats.com/eintracht-frankfurt/germany/team/22" },
 { team_name: "FC Augsburg", league: "bundesliga", friendly_name: "fc_augsburg", url: "https://corner-stats.com/augsburg/germany/team/36" },
 { team_name: "FC Bayern Munchen", league: "bundesliga", friendly_name: "fc_bayern_munchen", url: "https://corner-stats.com/bayern-munich/germany/team/21" },
 { team_name: "FC Schalke", league: "bundesliga", friendly_name: "schalke", url: "https://corner-stats.com/schalke/germany/team/24" },
 { team_name: "Hamburger SV", league: "bundesliga", friendly_name: "hamburger_sv", url: "https://corner-stats.com/hamburg/germany/team/35" },
 { team_name: "Hannover 96", league: "bundesliga", friendly_name: "hannover_96", url: "https://corner-stats.com/hannover-96/germany/team/23" },
 { team_name: "Hertha Berlin", league: "bundesliga", friendly_name: "hertha_berlin", url: "https://corner-stats.com/hertha-berlin/germany/team/1506" },
 { team_name: "RB Leipzig", league: "bundesliga", friendly_name: "leipzig", url: "https://corner-stats.com/rb-leipzig/germany/team/1892" },
 { team_name: "SV Werder Bremen", league: "bundesliga", friendly_name: "werder_bremen", url: "https://corner-stats.com/werder-bremen/germany/team/30" },
 { team_name: "SC Freiburg", league: "bundesliga", friendly_name: "freiburg", url: "https://corner-stats.com/sc-freiburg/germany/team/34" },
 { team_name: "TSG 1899 Hoffenheim", league: "bundesliga", friendly_name: "hoffenheim", url: "https://corner-stats.com/tsg-hoffenheim/germany/team/37" },
 { team_name: "Vfb Stuttgart", league: "bundesliga", friendly_name: "stuttgart", url: "https://corner-stats.com/vfb-stuttgart/germany/team/38" },
 { team_name: "Vfl Wolfsburg", league: "bundesliga", friendly_name: "wolfsburg", url: "https://corner-stats.com/wolfsburg/germany/team/32" }
],
bundesliga_2: [
 { team_name: "Erzgebirge Aue", league: "bundesliga_2", friendly_name: "erzgebirge_aue", url: "https://corner-stats.com/erzgebirge-aue/germany/team/1643"},
 { team_name: "Arminia Bielefeld", league: "bundesliga_2", friendly_name: "arminia_bielefeld", url: "https://corner-stats.com/arminia-bielefeld/germany/team/1514"},
 { team_name: "VFL Bochum", league: "bundesliga_2", friendly_name: "vfl_bochum", url: "https://corner-stats.com/bochum/germany/team/1505"},
 { team_name: "Eintracht Braunschweig", league: "bundesliga_2", friendly_name: "eintract_braunschweig", url: "https://corner-stats.com/eintracht-braunschweig/germany/team/1513" },
 { team_name: "Darmstadt 98", league: "bundesliga_2", friendly_name: "darmstadt_98", url: "https://corner-stats.com/darmstadt/germany/team/1507" },
 { team_name: "Dynamo Dresden", league: "bundesliga_2", friendly_name: "dynamo_dresden", url: "https://corner-stats.com/dynamo-dresden/germany/team/1508" },
 { team_name: "MSV Duisburg", league: "bundesliga_2", friendly_name: "msv_duisburg", url: "https://corner-stats.com/msv-duisburg/germany/team/1733" },
 { team_name: "Fortuna Dusseldorf", league: "bundesliga_2", friendly_name: "fortuna_dusseldorf", url: "https://corner-stats.com/fortuna-dusseldorf/germany/team/25" },
 { team_name: "SpVgg Greuther Furth", league: "bundesliga_2", friendly_name: "spvgg_greuther_furth", url: "https://corner-stats.com/spvgg-bayreuth/germany/team/1999" },
 { team_name: "FC Heidenheim", league: "bundesliga_2", friendly_name: "fc_heidenheim", url: "https://corner-stats.com/heidenheim/germany/team/1859" },
 { team_name: "FC Ingolstadt", league: "bundesliga_2", friendly_name: "fc_ingolstadt", url: "https://corner-stats.com/fc-ingolstadt/germany/team/1511" },
 { team_name: "FC Kaiserslautern", league: "bundesliga_2", friendly_name: "fc_kaiserslautern", url: "https://corner-stats.com/kaiserslautern/germany/team/1678" },
 { team_name: "Holstein Kiel", league: "bundesliga_2", friendly_name: "holstein_kiel", url: "https://corner-stats.com/holstein-kiel/germany/team/2430" },
 { team_name: "FC Nurnberg", league: "bundesliga_2", friendly_name: "fc_nurnberg", url: "https://corner-stats.com/nurnberg/germany/team/28" },
 { team_name: "Jahn Regensburg", league: "bundesliga_2", friendly_name: "jahn_regensburg", url: "https://corner-stats.com/jahn-regensburg/germany/team/2433" },
 { team_name: "SV Sandhausen", league: "bundesliga_2", friendly_name: "sv_sandhausen", url: "https://corner-stats.com/sandhausen/germany/team/1655" },
 { team_name: "FC St Pauli", league: "bundesliga_2", friendly_name: "fc_st_pauli", url: "https://corner-stats.com/st-pauli/germany/team/1509" },
 { team_name: "Union Berlin", league: "bundesliga_2", friendly_name: "union_berlin", url: "https://corner-stats.com/union-berlin/germany/team/1515" }
],
la_liga: [
 { team_name: "Alaves", league: "la_liga", friendly_name: "alaves", url: "https://corner-stats.com/cd-alaves/spain/team/1618"},
 { team_name: "Athletic Bilbao", league: "la_liga", friendly_name: "athletic_bilbao", url: "https://corner-stats.com/athletic-bilbao/spain/team/74"},
 { team_name: "Atletico Madrid", league: "la_liga", friendly_name: "atletico_madrid", url: "https://corner-stats.com/atletico-madrid/spain/team/67"},
 { team_name: "Barcelona", league: "la_liga", friendly_name: "barcelona", url: "https://corner-stats.com/barcelona/spain/team/59" },
 { team_name: "Real Betis", league: "la_liga", friendly_name: "real_betis", url: "https://corner-stats.com/real-betis/spain/team/70" },
 { team_name: "Celta Vigo", league: "la_liga", friendly_name: "celta_vigo", url: "https://corner-stats.com/celta-vigo/spain/team/73" },
 { team_name: "Eibar", league: "la_liga", friendly_name: "eibar", url: "https://corner-stats.com/eibar/spain/team/1658" },
 { team_name: "Espanyol", league: "la_liga", friendly_name: "espanyol", url: "https://corner-stats.com/espanyol/spain/team/77" },
 { team_name: "Getafe", league: "la_liga", friendly_name: "getafe", url: "https://corner-stats.com/getafe/spain/team/66" },
 { team_name: "Girona", league: "la_liga", friendly_name: "girona", url: "https://corner-stats.com/girona/spain/team/1676" },
 { team_name: "Deportivo La Coruna", league: "la_liga", friendly_name: "la_coruna", url: "https://corner-stats.com/d-coruna/spain/team/64" },
 { team_name: "Las Palmas", league: "la_liga", friendly_name: "las_palmas", url: "https://corner-stats.com/las-palmas/spain/team/1680" },
 { team_name: "Leganes", league: "la_liga", friendly_name: "leganes", url: "https://corner-stats.com/leganes/spain/team/2028" },
 { team_name: "Levante", league: "la_liga", friendly_name: "levante", url: "https://corner-stats.com/levante/spain/team/68" },
 { team_name: "Malaga", league: "la_liga", friendly_name: "malaga", url: "https://corner-stats.com/malaga/spain/team/61" },
 { team_name: "Real Madrid", league: "la_liga", friendly_name: "real_madrid", url: "https://corner-stats.com/real-madrid/spain/team/69" },
 { team_name: "Real Sociedad", league: "la_liga", friendly_name: "real_sociedad", url: "https://corner-stats.com/real-sociedad/spain/team/71" },
 { team_name: "Sevilla", league: "la_liga", friendly_name: "sevilla", url: "https://corner-stats.com/sevilla/spain/team/65" },
 { team_name: "Valencia", league: "la_liga", friendly_name: "valencia", url: "https://corner-stats.com/valencia/spain/team/75" },
 { team_name: "Villarreal", league: "la_liga", friendly_name: "villarreal", url: "https://corner-stats.com/villarreal/spain/team/1550" }
],
portugal_premier_league: [
 { team_name: "Aves", league: "portugal_premier_league", friendly_name: "aves", url: "https://corner-stats.com/cd-aves/portugal/team/3366" },
 { team_name: "Belenenses", league: "portugal_premier_league", friendly_name: "belenenses", url: "https://corner-stats.com/belenenses/portugal/team/2265" },
 { team_name: "Benfica", league: "portugal_premier_league", friendly_name: "benfica", url: "https://corner-stats.com/benfica/portugal/team/172"},
 { team_name: "Boavista", league: "portugal_premier_league", friendly_name: "boavista", url: "https://corner-stats.com/boavista/portugal/team/2282" },
 { team_name: "Chaves", league: "portugal_premier_league", friendly_name: "chaves", url: "https://corner-stats.com/gd-chaves/portugal/team/3320" },
 { team_name: "Estoril", league: "portugal_premier_league", friendly_name: "estoril", url: "https://corner-stats.com/estoril/portugal/team/1549" },
 { team_name: "Feirense", league: "portugal_premier_league", friendly_name: "feirense", url: "https://corner-stats.com/cd-feirense/portugal/team/3936" },
 { team_name: "Porto", league: "portugal_premier_league", friendly_name: "porto", url: "https://corner-stats.com/fc-porto/portugal/team/1626"},
 { team_name: "Guimaraes", league: "portugal_premier_league", friendly_name: "guimaraes", url: "https://corner-stats.com/guimaraes/portugal/team/1634" },
 { team_name: "Maritimo", league: "portugal_premier_league", friendly_name: "maritimo", url: "https://corner-stats.com/maritimo/portugal/team/2264" },
 { team_name: "Moreirense", league: "portugal_premier_league", friendly_name: "moreirense", url: "https://corner-stats.com/moreirense/portugal/team/2362" },
 { team_name: "Pacos Ferreira	", league: "portugal_premier_league", friendly_name: "pacos_ferreira	", url: "https://corner-stats.com/pacos-ferreira/portugal/team/1528" },
 { team_name: "Portimonense", league: "portugal_premier_league", friendly_name: "portimonense", url: "https://corner-stats.com/portimonense-sc/portugal/team/4558" },
 { team_name: "Sporting Braga", league: "portugal_premier_league", friendly_name: "sporting_braga", url: "https://corner-stats.com/braga/portugal/team/2053"},
 { team_name: "Sporting CP", league: "portugal_premier_league", friendly_name: "sporting_cp", url: "https://corner-stats.com/sporting/portugal/team/2050" },
 { team_name: "Tondela", league: "portugal_premier_league", friendly_name: "tondela", url: "https://corner-stats.com/cd-tondela/portugal/team/3463" },
 { team_name: "Vitoria Setubal", league: "portugal_premier_league", friendly_name: "vitoria_setubal", url: "https://corner-stats.com/vitoria-setubal/portugal/team/2023" }
],
poland_ekstraklasa: [
 { team_name: "Arka Gdynia", league: "poland_ekstraklasa", friendly_name: "arka_gdynia", url: "https://corner-stats.com/arka-gdynia/poland/team/3950" },
 { team_name: "Cracovia Krakow", league: "poland_ekstraklasa", friendly_name: "cracovia_krakow", url: "https://corner-stats.com/cracovia-krakow/poland/team/2585" },
 { team_name: "Gornik Zabrze", league: "poland_ekstraklasa", friendly_name: "gornik_zabrze", url: "https://corner-stats.com/gornik-zabrze/poland/team/2459" },
 { team_name: "Jagiellonia Bialystok", league: "poland_ekstraklasa", friendly_name: "jagiellonia_bialystok", url: "https://corner-stats.com/jagiellonia-bialystok/poland/team/2410"},
 { team_name: "Korona Kielce", league: "poland_ekstraklasa", friendly_name: "korona_kielce", url: "https://corner-stats.com/korona-kielce/poland/team/2550" },
 { team_name: "Lech Poznan", league: "poland_ekstraklasa", friendly_name: "lech_poznan", url: "https://corner-stats.com/lech-poznan/poland/team/1778"},
 { team_name: "Lechia Gdansk", league: "poland_ekstraklasa", friendly_name: "lechia_gdansk", url: "https://corner-stats.com/lechia-gdansk/poland/team/2116" },
 { team_name: "Legia Warszawa", league: "poland_ekstraklasa", friendly_name: "legia_warszawa", url: "https://corner-stats.com/legia-warsaw/poland/team/1525"},
 { team_name: "Nieciecza", league: "poland_ekstraklasa", friendly_name: "nieciecza", url: "https://corner-stats.com/termalica-niec/poland/team/3110" },
 { team_name: "Pogon Szczecin", league: "poland_ekstraklasa", friendly_name: "pogon_szczecin", url: "https://corner-stats.com/pogon-szczecin/poland/team/1834" },
 { team_name: "Piast Gliwice", league: "poland_ekstraklasa", friendly_name: "piast_gilwice", url: "https://corner-stats.com/piast-gliwice/poland/team/2458" },
 { team_name: "Slask Wroclaw", league: "poland_ekstraklasa", friendly_name: "slask_wroclaw", url: "https://corner-stats.com/slask-wroclaw/poland/team/2049" },
 { team_name: "Sandecja Nowy Saqz", league: "poland_ekstraklasa", friendly_name: "sandecja_nowy_saqz", url: "https://corner-stats.com/sandecja-ns/poland/team/3766" },
 { team_name: "Wisla Plock", league: "poland_ekstraklasa", friendly_name: "wisla_plock", url: "https://corner-stats.com/wisla-plock-sa/poland/team/3129" },
 { team_name: "Wisla Krakow", league: "poland_ekstraklasa", friendly_name: "wisla_krakow", url: "https://corner-stats.com/wisla-krakow/poland/team/2189" },
 { team_name: "Zaglebie Lubin", league: "poland_ekstraklasa", friendly_name: "Zaglebie Lubin", url: "https://corner-stats.com/zaglebie-lubin/poland/team/332" }
],
a_league: [
 { team_name: "Adelaide United", league: "a_league", friendly_name: "adelaide_united", url: "https://corner-stats.com/adelaide-united/australia/team/641"},
 { team_name: "Brisbane Roar", league: "a_league", friendly_name: "brisbane_roar", url: "https://corner-stats.com/brisbane-roar/australia/team/2196"},
 { team_name: "Central Coast Mariners", league: "a_league", friendly_name: "central_coast_mariners", url: "https://corner-stats.com/central-coast-mariners/australia/team/1481"},
 { team_name: "Melbourne City", league: "a_league", friendly_name: "melbourne_city", url: "https://corner-stats.com/melbourne-heart/australia/team/702" },
 { team_name: "Melbourne Victory", league: "a_league", friendly_name: "melbourne_victory", url: "https://corner-stats.com/melbourne-victory/australia/team/1806" },
 { team_name: "Newcastle Jets", league: "a_league", friendly_name: "newcastle_jets", url: "https://corner-stats.com/newcastle-jets/australia/team/2394" },
 { team_name: "Perth Glory", league: "a_league", friendly_name: "perth_glory", url: "https://corner-stats.com/perth-glory/australia/team/2012" },
 { team_name: "Sydney FC", league: "a_league", friendly_name: "sydney_fc", url: "https://corner-stats.com/sydney-fc/australia/team/1937" },
 { team_name: "Wellington Phoenix", league: "a_league", friendly_name: "wellington_phoenix", url: "https://corner-stats.com/wellington-phoenix/new-zealand/team/1936" },
 { team_name: "Western Sydney Wanderers", league: "a_league", friendly_name: "western_city_wanderers", url: "https://corner-stats.com/western-sydney-wanderers/australia/team/1739" }
],
ligue_1: [
 { team_name: "Amiens", league: "ligue_1", friendly_name: "amiens", url: "https://corner-stats.com/amiens-sc/france/team/573"},
 { team_name: "Angers", league: "ligue_1", friendly_name: "angers", url: "https://corner-stats.com/angers/france/team/1568"},
 { team_name: "AS Monaco", league: "ligue_1", friendly_name: "monaco", url: "https://corner-stats.com/monaco/monaco/team/1556"},
 { team_name: "AS Saint-Etienne", league: "ligue_1", friendly_name: "saint_etienne", url: "https://corner-stats.com/st-etienne/france/team/85" },
 { team_name: "Dijon", league: "ligue_1", friendly_name: "dijon", url: "https://corner-stats.com/dijon/france/team/1624" },
 { team_name: "Guingamp", league: "ligue_1", friendly_name: "guingamp", url: "https://corner-stats.com/guingamp/france/team/1558" },
 { team_name: "Troyes", league: "ligue_1", friendly_name: "troyes", url: "https://corner-stats.com/troyes/france/team/97" },
 { team_name: "FC Metz", league: "ligue_1", friendly_name: "fc_metz", url: "https://corner-stats.com/metz/france/team/1564" },
 { team_name: "FC Nantes", league: "ligue_1", friendly_name: "fc_nantes", url: "https://corner-stats.com/nantes/france/team/1555" },
 { team_name: "Bordeaux", league: "ligue_1", friendly_name: "bordeaux", url: "https://corner-stats.com/bordeaux/france/team/82" },
 { team_name: "Lille", league: "ligue_1", friendly_name: "lille", url: "https://corner-stats.com/lille/france/team/89" },
 { team_name: "Montpellier", league: "ligue_1", friendly_name: "montpellier", url: "https://corner-stats.com/montpellier/france/team/91" },
 { team_name: "Nice", league: "ligue_1", friendly_name: "nice", url: "https://corner-stats.com/nice/france/team/94" },
 { team_name: "Lyon", league: "ligue_1", friendly_name: "lyon", url: "https://corner-stats.com/lyon/france/team/80" },
 { team_name: "Marseille", league: "ligue_1", friendly_name: "marseille", url: "https://corner-stats.com/marseille/france/team/79" },
 { team_name: "Paris Saint-Germain", league: "ligue_1", friendly_name: "psg", url: "https://corner-stats.com/psg/france/team/86" },
 { team_name: "Strasbourg", league: "ligue_1", friendly_name: "strasbourg", url: "https://corner-stats.com/rc-strasbourg/france/team/1686" },
 { team_name: "Caen", league: "ligue_1", friendly_name: "caen", url: "https://corner-stats.com/caen/france/team/1640" },
 { team_name: "Stade Rennes", league: "ligue_1", friendly_name: "stade_rennes", url: "https://corner-stats.com/rennes/france/team/95" },
 { team_name: "Toulouse", league: "ligue_1", friendly_name: "toulouse", url: "https://corner-stats.com/toulouse/france/team/83" }
],
ligue_2: [
 { team_name: "AJ Ajaccio", league: "ligue_2", friendly_name: "aj_ajaccio", url: "https://corner-stats.com/ac-ajaccio/france/team/90"},
 { team_name: "Auxerre", league: "ligue_2", friendly_name: "auxerre", url: "https://corner-stats.com/auxerre/france/team/1559"},
 { team_name: "Bourg-en-Bresse", league: "ligue_2", friendly_name: "bourg_en_bresse", url: "https://corner-stats.com/bourg-peronnas/france/team/896"},
 { team_name: "Brest", league: "ligue_2", friendly_name: "brest", url: "https://corner-stats.com/brest/france/team/88" },
 { team_name: "Chateauroux", league: "ligue_2", friendly_name: "chateauroux", url: "https://corner-stats.com/chateauroux/france/team/563" },
 { team_name: "Clermont Foot", league: "ligue_2", friendly_name: "clermont_foot", url: "https://corner-stats.com/clermont-foot/france/team/1623" },
 { team_name: "Gazelec Ajaccio", league: "ligue_2", friendly_name: "gazalec_ajaccio", url: "https://corner-stats.com/ajaccio-gfca/france/team/1863" },
 { team_name: "Le Havre", league: "ligue_2", friendly_name: "le_havre", url: "https://corner-stats.com/le-havre/france/team/1639" },
 { team_name: "Lens", league: "ligue_2", friendly_name: "lens", url: "https://corner-stats.com/lens/france/team/569" },
 { team_name: "Lorient", league: "ligue_2", friendly_name: "lorient", url: "https://corner-stats.com/lorient/france/team/81" },
 { team_name: "Nancy", league: "ligue_2", friendly_name: "lille", url: "https://corner-stats.com/lille/france/team/89" },
 { team_name: "Nimes", league: "ligue_2", friendly_name: "nimes", url: "https://corner-stats.com/nimes/france/team/1653" },
 { team_name: "Niort", league: "ligue_2", friendly_name: "niort", url: "https://corner-stats.com/niort/france/team/1566" },
 { team_name: "Orleans", league: "ligue_2", friendly_name: "orleans", url: "https://corner-stats.com/us-orleans-45/france/team/1864" },
 { team_name: "Paris FC", league: "ligue_2", friendly_name: "paris_fc", url: "https://corner-stats.com/paris-fc/france/team/2018" },
 { team_name: "Reims", league: "ligue_2", friendly_name: "reims", url: "https://corner-stats.com/reims/france/team/92" },
 { team_name: "Sochaux", league: "ligue_2", friendly_name: "sochaux", url: "https://corner-stats.com/sochaux/france/team/98" },
 { team_name: "Tours", league: "ligue_2", friendly_name: "tours", url: "https://corner-stats.com/tours/france/team/1563" },
 { team_name: "Valenciennes", league: "ligue_2", friendly_name: "valenciennes", url: "https://corner-stats.com/valenciennes/france/team/84" }
],
j_league: [
 { team_name: "Consadole Sapporo", search_name: 'Consadole Sapporo', league: "Japan J-League", friendly_name: "consadole_sapporo", url: "https://corner-stats.com/consadole-sapporo/japan/team/148", id: '2377'},
 { team_name: "Vegalta Sendai", search_name: 'Vegalta Sendai', league: "Japan J-League", friendly_name: "vegalta_sendai", url: "https://corner-stats.com/sendai/japan/team/131", id: '3541'},
 { team_name: "Kashima Antlers", search_name: 'Kashima Antlers', league: "Japan J-League", friendly_name: "kashima_antlers", url: "https://corner-stats.com/kashima-antlers/japan/team/142", id: '1466'},
 { team_name: "Urawa Red Diamonds", search_name: 'Urawa Red Diamonds', league: "Japan J-League", friendly_name: "urawa_red_diamonds", url: "https://corner-stats.com/urawa-red-diamonds/japan/team/133", id: '2641' },
 { team_name: " Kashiwa Reysol", search_name: 'Kashiwa Reysol', league: "Japan J-League", friendly_name: "kashiwa_reysol", url: "https://corner-stats.com/kashiwa-reysol/japan/team/138", id: '2367' },
 { team_name: "FC Tokyo", search_name: 'FC Tokyo', league: "Japan J-League", friendly_name: "fc_tokyo", url: "https://corner-stats.com/fc-tokyo/japan/team/139", id: '2640' },
 { team_name: "Kawasaki Frontale", search_name: 'Kawasaki Frontale', league: "Japan J-League", friendly_name: "kawasaki_frontale", url: "https://corner-stats.com/kawasaki-frontale/japan/team/143", id: '2364' },
 { team_name: "Yokohama F. Marinos", search_name: 'Yokohama F-Marinos', league: "Japan J-League", friendly_name: "yokohama_marinos", url: "https://corner-stats.com/yokohama-f-marinos/japan/team/140", id: '2362' },
 { team_name: "Shonan Bellmare", search_name: 'Shonan Bellmare', league: "Japan J-League", friendly_name: "shonan_bellmare", url: "https://corner-stats.com/shonan-bellmare/japan/team/222", id: '2378' },
 { team_name: "Shimizu S-Pulse", search_name: 'Shimizu S-Pulse', league: "Japan J-League", friendly_name: "shimizu_pulse", url: "https://corner-stats.com/shimizu-s-pulse/japan/team/137", id: '2368' },
 { team_name: "Jubilo Iwata", search_name: 'Jubilo Iwata', league: "Japan J-League", friendly_name: "jubilo_iwata", url: "https://corner-stats.com/jubilo-iwata/japan/team/134", id: '2636' },
 { team_name: "Nagoya Grampus", search_name: 'Nagoya Grampus', league: "Japan J-League", friendly_name: "nagoya_grampus", url: "https://corner-stats.com/nagoya-grampus/japan/team/136", id: '1469' },
 { team_name: "Gamba Osaka", search_name: 'Gamba Osaka', league: "Japan J-League", friendly_name: "gamba_osaka", url: "https://corner-stats.com/gamba-osaka/japan/team/145", id: '1584' },
 { team_name: "Cerezo Osaka", search_name: 'Cerezo Osaka', league: "Japan J-League", friendly_name: "cerezo_osaka", url: "https://corner-stats.com/cerezo-osaka/japan/team/144", id: '1588' },
 { team_name: "Vissel Kobe", search_name: 'Vissel Kobe', league: "Japan J-League", friendly_name: "vissel_kobe", url: "https://corner-stats.com/vissel-kobe/japan/team/141", id: '2371' },
 { team_name: "Sanfrecce Hiroshima", search_name: 'Sanfrecce Hiroshima', league: "Japan J-League", friendly_name: "sanfrecce_hiroshima", url: "https://corner-stats.com/sanfrecce-hiroshima/japan/team/132", id: '2561' },
 { team_name: "Sagan Tosu", search_name: 'Sagan Tosu', league: "Japan J-League", friendly_name: "sagan_tosu", url: "https://corner-stats.com/sagan-tosu/japan/team/135", id: '2554' },
 { team_name: "V-Varen Nagasaki", search_name: 'V-Varen Nagasaki', league: "Japan J-League", friendly_name: "v_nagasaki", url: "https://corner-stats.com/v-varen-nagasak/japan/team/1816", id: '10425' }
],
k_league: [
 { team_name: "Daegu FC", league: "k_league", friendly_name: "daegu_fc", url: "https://corner-stats.com/daegu-fc/korea-republic/team/4195"},
 { team_name: "Gangwon FC", league: "k_league", friendly_name: "gangwon_fc", url: "https://corner-stats.com/gangwon-fc/korea-republic/team/3504"},
 { team_name: "Gyeongnam FC", league: "k_league", friendly_name: "gyeongnam_fc", url: "https://corner-stats.com/gyeongnam-fc/korea-republic/team/2797"},
 { team_name: "Incheon United", league: "k_league", friendly_name: "incheon_united", url: "https://corner-stats.com/incheon-utd/korea-republic/team/2683" },
 { team_name: "Jeju United", league: "k_league", friendly_name: "jeju_united", url: "https://corner-stats.com/jeju-united/korea-republic/team/1081" },
 { team_name: "Jeonbuk Hyundai Motors", league: "k_league", friendly_name: "jeonbuk_hyundai_motors", url: "https://corner-stats.com/jeonbuk-motors/korea-republic/team/644" },
 { team_name: "Jeonnam Dragons", league: "k_league", friendly_name: "jeonnam_dragons", url: "https://corner-stats.com/jeonnam-dragons/korea-republic/team/2664" },
 { team_name: "Pohang Steelers", league: "k_league", friendly_name: "pohang_steelers", url: "https://corner-stats.com/pohang-steelers/korea-republic/team/653" },
 { team_name: "Sangju Sangmu", league: "k_league", friendly_name: "sangju_sangmu", url: "https://corner-stats.com/sangju-sangmu-p/korea-republic/team/2796" },
 { team_name: "FC Seoul", league: "k_league", friendly_name: "fc_seoul", url: "https://corner-stats.com/fc-seoul/korea-republic/team/1062" },
 { team_name: "Suwon Samsung Bluewings", league: "k_league", friendly_name: "suwon_samsung_bluewings", url: "https://corner-stats.com/suwon-bluewings/korea-republic/team/1063" },
 { team_name: "Ulsan Hyundai", league: "k_league", friendly_name: "ulsan_hyundai", url: "https://corner-stats.com/ulsan-hyundai-h/korea-republic/team/1738" }
],
super_lig: [
 { team_name: "Sivasspor", league: "super_lig", friendly_name: "sivasspor", url: "https://corner-stats.com/sivasspor/turkey/team/2335"},
 { team_name: "Akhisar Bld", league: "super_lig", friendly_name: "ahkisar_bld", url: "https://corner-stats.com/akhisar-belediye/turkey/team/2056"},
 { team_name: "Alanyaspor", league: "super_lig", friendly_name: "alanyaspor", url: "https://corner-stats.com/alanyaspor/turkey/team/735"},
 { team_name: "Antalyaspor", league: "super_lig", friendly_name: "antalyaspor", url: "https://corner-stats.com/antalyaspor/turkey/team/236" },
 { team_name: "Beskitas", league: "super_lig", friendly_name: "besiktas", url: "https://corner-stats.com/besiktas/turkey/team/1723" },
 { team_name: "Bursaspor", league: "super_lig", friendly_name: "bursaspor", url: "https://corner-stats.com/bursaspor/turkey/team/2092" },
 { team_name: "Yeni Malatyaspor", league: "super_lig", friendly_name: "yeni_malatyaspor", url: "https://corner-stats.com/yeni-malatyasp/turkey/team/4564" },
 { team_name: "Fenerbahce", league: "super_lig", friendly_name: "fenerbahce", url: "https://corner-stats.com/fenerbahce/turkey/team/177" },
 { team_name: "Galatasaray", league: "super_lig", friendly_name: "galatasaray", url: "https://corner-stats.com/galatasaray/turkey/team/156" },
 { team_name: "Goztepe", league: "super_lig", friendly_name: "goztepe", url: "https://corner-stats.com/goztepe-as-izmir/turkey/team/5728" },
 { team_name: "Genclerbirligi", league: "super_lig", friendly_name: "genclerbirligi", url: "https://corner-stats.com/genclerbirligi/turkey/team/2270" },
 { team_name: "Basaksehir FK", league: "super_lig", friendly_name: "basaksehir", url: "https://corner-stats.com/istanbul-basaksehir/turkey/team/2363" },
 { team_name: "Karabukspor", league: "super_lig", friendly_name: "karabukspor", url: "https://corner-stats.com/karabukspor/turkey/team/2077" },
 { team_name: "Kasimpasa", league: "super_lig", friendly_name: "kasimpasa", url: "https://corner-stats.com/kasimpasa/turkey/team/1745" },
 { team_name: "Kayserispor", league: "super_lig", friendly_name: "kayserispor", url: "https://corner-stats.com/kayserispor/turkey/team/850" },
 { team_name: "Konyaspor", league: "super_lig", friendly_name: "konyaspor", url: "https://corner-stats.com/konyaspor/turkey/team/2336" },
 { team_name: "Osmanlispor", league: "super_lig", friendly_name: "osmanlispor", url: "https://corner-stats.com/osmanlispor/turkey/team/4525" },
 { team_name: "Trabzonspor", league: "super_lig", friendly_name: "Trabzonspor", url: "https://corner-stats.com/trabzonspor/turkey/team/1631" }
],
swiss_super_lig: [
 { team_name: "FC Basel", league: "swiss_super_lig", friendly_name: "fc_basel", url: "https://corner-stats.com/basel/switzerland/team/258"},
 { team_name: "Grasshopper Club Zurich", league: "swiss_super_lig", friendly_name: "grasshopper", url: "https://corner-stats.com/grasshoppers/switzerland/team/1924"},
 { team_name: "FC Lausanne-Sport", league: "swiss_super_lig", friendly_name: "lausanne_sport", url: "https://corner-stats.com/lausanne-sport/switzerland/team/722"},
 { team_name: "FC Lugano", league: "swiss_super_lig", friendly_name: "lugano", url: "https://corner-stats.com/fc-lugano/switzerland/team/1767" },
 { team_name: "FC Luzern", league: "swiss_super_lig", friendly_name: "luzern", url: "https://corner-stats.com/lucerne/switzerland/team/1728" },
 { team_name: "FC Sion", league: "swiss_super_lig", friendly_name: "sion", url: "https://corner-stats.com/fc-sion/switzerland/team/1926" },
 { team_name: "FC St Gallen", league: "swiss_super_lig", friendly_name: "gallen", url: "https://corner-stats.com/st-gallen/switzerland/team/1579" },
 { team_name: "FC Thun", league: "swiss_super_lig", friendly_name: "thun", url: "https://corner-stats.com/fc-thun/switzerland/team/1647" },
 { team_name: "BSC Young Boys", league: "swiss_super_lig", friendly_name: "young_boys", url: "https://corner-stats.com/young-boys/switzerland/team/1699" },
 { team_name: "FC Zurich", league: "swiss_super_lig", friendly_name: "zurich", url: "https://corner-stats.com/fc-zurich/switzerland/team/1729" }
],
norway_eliteserien: [
 { team_name: "Bodo/Glimt", league: "norway_eliteserien", friendly_name: "fc_basel", url: "https://corner-stats.com/fk-bodo-glimt/norway/team/2802"},
 { team_name: "Brann", league: "norway_eliteserien", friendly_name: "brann", url: "https://corner-stats.com/sk-brann/norway/team/2801"},
 { team_name: "Haugesund", league: "norway_eliteserien", friendly_name: "haugesund", url: "https://corner-stats.com/fk-haugesund/norway/team/2800"},
 { team_name: "Kristiansund", league: "norway_eliteserien", friendly_name: "kristiansund", url: "https://corner-stats.com/kristiansund-bk/norway/team/3024" },
 { team_name: "Lillestrom", league: "norway_eliteserien", friendly_name: "lillestrom", url: "https://corner-stats.com/lillestrom-sk/norway/team/969" },
 { team_name: "Molde", league: "norway_eliteserien", friendly_name: "molde", url: "https://corner-stats.com/molde-fk/norway/team/1801" },
 { team_name: "Odd", league: "norway_eliteserien", friendly_name: "odd", url: "https://corner-stats.com/odd-grenland-bk/norway/team/965" },
 { team_name: "Ranheim", league: "norway_eliteserien", friendly_name: "ranheim", url: "https://corner-stats.com/ranheim-fotball/norway/team/2980" },
 { team_name: "Rosenborg", league: "norway_eliteserien", friendly_name: "rosenborg", url: "https://corner-stats.com/rosenborg/norway/team/303" },
 { team_name: "Sandefjord", league: "norway_eliteserien", friendly_name: "sandefjord", url: "https://corner-stats.com/sandefjord/norway/team/2946" },
 { team_name: "Sarpsborg 08", league: "norway_eliteserien", friendly_name: "sarpsborg_08", url: "https://corner-stats.com/sarpsborg-08-ff/norway/team/2806" },
 { team_name: "Stabaek", league: "norway_eliteserien", friendly_name: "stabaek", url: "https://corner-stats.com/stabek-fotball/norway/team/2805" },
 { team_name: "Start", league: "norway_eliteserien", friendly_name: "start", url: "https://corner-stats.com/young-boys/switzerland/team/1699" },
 { team_name: "Stromsgodset", league: "norway_eliteserien", friendly_name: "stromsgodset", url: "https://corner-stats.com/stromsgodset-if/norway/team/1798" },
 { team_name: "Tromso", league: "norway_eliteserien", friendly_name: "tromso", url: "https://corner-stats.com/tromso-il/norway/team/1497" },
 { team_name: "Valerenga", league: "norway_eliteserien", friendly_name: "valerenga", url: "https://corner-stats.com/valerenga/norway/team/403" }
],
sweden_allsvenskan: [
 { team_name: "AIK", league: "sweden_allsvenskan", friendly_name: "aik", url: "https://corner-stats.com/aik/sweden/team/170" },
 { team_name: "Brommapojkarna", league: "sweden_allsvenskan", friendly_name: "brommapojkarna", url: "https://corner-stats.com/brommapojkarna/sweden/team/2035" },
 { team_name: "Dalkurd", league: "sweden_allsvenskan", friendly_name: "dalkurd", url: "https://corner-stats.com/dalkurd-ff/sweden/team/3008" },
 { team_name: "Djurgarden", league: "sweden_allsvenskan", friendly_name: "djurgarden", url: "https://corner-stats.com/djurgardens-if/sweden/team/1795" },
 { team_name: "Elfsborg", league: "sweden_allsvenskan", friendly_name: "elfsborg", url: "https://corner-stats.com/elfsborg/sweden/team/1771" },
 { team_name: "GIF Sundsvall", league: "sweden_allsvenskan", friendly_name: "gif_sundsvall", url: "https://corner-stats.com/gif-sundsvall/sweden/team/1773" },
 { team_name: "Hacken", league: "sweden_allsvenskan", friendly_name: "hacken", url: "https://corner-stats.com/bk-hacken/sweden/team/2814" },
 { team_name: "Hammarby", league: "sweden_allsvenskan", friendly_name: "hammarby", url: "https://corner-stats.com/hammarby-if/sweden/team/836"},
 { team_name: "IFK Goteborg", league: "sweden_allsvenskan", friendly_name: "ifk_goteborg", url: "https://corner-stats.com/ifk-goteborg/sweden/team/2178" },
 { team_name: "Kalmar", league: "sweden_allsvenskan", friendly_name: "kalmar", url: "https://corner-stats.com/kalmar-ff/sweden/team/2810" },
 { team_name: "Malmo FF", league: "sweden_allsvenskan", friendly_name: "malmo_ff", url: "https://corner-stats.com/malmo-ff/sweden/team/2109"},
 { team_name: "Norrkoping", league: "sweden_allsvenskan", friendly_name: "norrkoping", url: "https://corner-stats.com/ifk-norrkoping/sweden/team/282" },
 { team_name: "Orebro", league: "sweden_allsvenskan", friendly_name: "orebro", url: "https://corner-stats.com/orebro-sk/sweden/team/2190"},
 { team_name: "Ostersunds FK", league: "sweden_allsvenskan", friendly_name: "osterunds_fk", url: "https://corner-stats.com/ostersunds-fk/sweden/team/688" },
 { team_name: "Sirius", league: "sweden_allsvenskan", friendly_name: "sirius", url: "https://corner-stats.com/ik-sirius/sweden/team/3021" },
 { team_name: "Trelleborg", league: "sweden_allsvenskan", friendly_name: "trelleborg", url: "https://corner-stats.com/trelleborgs-ff/sweden/team/4664" }
],
mls_league: [
 { team_name: "Atlanta United", league: "mls_league", friendly_name: "atlanta_united", url: "https://corner-stats.com/atlanta-united/united-states/team/5833"},
 { team_name: "Chicago Fire", league: "mls_league", friendly_name: "chicago_fire", url: "https://corner-stats.com/chicago-fire/united-states/team/1962"},
 { team_name: "Colorado Rapids", league: "mls_league", friendly_name: "colorado_rapids", url: "https://corner-stats.com/colorado-rapids/united-states/team/2494"},
 { team_name: "Columbus Crew SC", league: "mls_league", friendly_name: "columbus_crew", url: "https://corner-stats.com/columbus-crew/united-states/team/2562" },
 { team_name: "DC United", league: "mls_league", friendly_name: "dc_united", url: "https://corner-stats.com/dc-united/united-states/team/2491" },
 { team_name: "FC Dallas", league: "mls_league", friendly_name: "fc_dallas", url: "https://corner-stats.com/fc-dallas/united-states/team/1941" },
 { team_name: "Houston Dynamo", league: "mls_league", friendly_name: "houston_dynamo", url: "https://corner-stats.com/houston-dynamo/united-states/team/1942" },
 { team_name: "LA Galaxy", league: "mls_league", friendly_name: "la_galaxy", url: "https://corner-stats.com/la-galaxy/united-states/team/2001" },
 { team_name: "Los Angeles FC", league: "mls_league", friendly_name: "los_angeles", url: "https://corner-stats.com/los-angeles-fc/united-states/team/6896" },
 { team_name: "Minnesota United FC", league: "mls_league", friendly_name: "minnesota_united", url: "https://corner-stats.com/minnesota-utd/united-states/team/1827" },
 { team_name: "Montreal Impact", league: "mls_league", friendly_name: "montreal_impact", url: "https://corner-stats.com/montreal-impact/canada/team/2492" },
 { team_name: "New England Revolution", league: "mls_league", friendly_name: "new_england_revolution", url: "https://corner-stats.com/new-england-revolution/united-states/team/2586" },
 { team_name: "New York City FC", league: "mls_league", friendly_name: "new_york_city_fc", url: "https://corner-stats.com/new-york-city-fc/united-states/team/2566" },
 { team_name: "New York Red Bulls", league: "mls_league", friendly_name: "new_york_red_bulls", url: "https://corner-stats.com/new-york-red-bulls/united-states/team/1939" },
 { team_name: "Orlando City SC", league: "mls_league", friendly_name: "orlando_city_sc", url: "https://corner-stats.com/orlando-city-sc/united-states/team/418" },
 { team_name: "Philadelphia Union", league: "mls_league", friendly_name: "philadelphia_union", url: "https://corner-stats.com/philadelphia-union/united-states/team/2493" },
 { team_name: "Portland Timbers", league: "mls_league", friendly_name: "portland_timbers", url: "https://corner-stats.com/portland-timbers/united-states/team/2563" },
 { team_name: "Real Salt Lake", league: "mls_league", friendly_name: "real_salt_lake", url: "https://corner-stats.com/real-salt-lake/united-states/team/2564" },
 { team_name: "San Jose Earthquakes", league: "mls_league", friendly_name: "san_jose_earthquakes", url: "https://corner-stats.com/san-jose-earthquakes/united-states/team/1838" },
 { team_name: "Seattle Sounders FC", league: "mls_league", friendly_name: "seattle_sounders", url: "https://corner-stats.com/seattle-sounders-fc/united-states/team/1960" },
 { team_name: "Sporting Kansas City", league: "mls_league", friendly_name: "sporting_kansas_city", url: "https://corner-stats.com/sporting-kansas-city/united-states/team/1935" },
 { team_name: "Toronto FC", league: "mls_league", friendly_name: "toronto_fc", url: "https://corner-stats.com/toronto-fc/canada/team/1961" },
 { team_name: "Vancouver Whitecaps FC", league: "mls_league", friendly_name: "vancouver_whitecaps", url: "https://corner-stats.com/vancouver-whitecaps/canada/team/2561" }
],
primera_division: [
 { team_name: "Alajuelense", league: "primera_division", friendly_name: "alajuelense", url: "https://corner-stats.com/alajuelense/costa-rica/team/2244"},
 { team_name: "Carmelita", league: "primera_division", friendly_name: "carmelita", url: "https://corner-stats.com/ad-carmelita/costa-rica/team/2239"},
 { team_name: "Cartagines", league: "primera_division", friendly_name: "cartagines", url: "https://corner-stats.com/cartagines/costa-rica/team/2246"},
 { team_name: "Grecia", league: "primera_division", friendly_name: "grecia", url: "https://corner-stats.com/grecia-fc/costa-rica/team/6261" },
 { team_name: "Guadalupe", league: "primera_division", friendly_name: "guadalupe", url: "https://corner-stats.com/guadalupe/costa-rica/team/6260" },
 { team_name: "Herediano", league: "primera_division", friendly_name: "herediano", url: "https://corner-stats.com/herediano/costa-rica/team/2355" },
 { team_name: "Liberia", league: "primera_division", friendly_name: "liberia", url: "https://corner-stats.com/municipal-lib/costa-rica/team/4369" },
 { team_name: "Limon", league: "primera_division", friendly_name: "limon", url: "https://corner-stats.com/limon-fc/costa-rica/team/2303" },
 { team_name: "Perez Zeledon", league: "primera_division", friendly_name: "perez_zeledon", url: "https://corner-stats.com/municipal-perez-zeledon/costa-rica/team/2242" },
 { team_name: "Santos de Guapiles", league: "primera_division", friendly_name: "santos_de_guapiles", url: "https://corner-stats.com/santos-de-guapiles/costa-rica/team/2243" },
 { team_name: "Saprissa", league: "primera_division", friendly_name: "saprissa", url: "https://corner-stats.com/deportivo-saprissa/costa-rica/team/2245" },
 { team_name: "UCR", league: "primera_division", friendly_name: "ucr", url: "https://corner-stats.com/universidad-de-costa-rica/costa-rica/team/2238" }
],
austria_bundesliga: [
 { team_name: "Admira Wacker Mödling", league: "austria_bundesliga", friendly_name: "admira_wacker_modling", url: "https://corner-stats.com/fc-trenkwalder-admira/austria/team/1893"},
 { team_name: "Austria Wien", league: "austria_bundesliga", friendly_name: "austria_wien", url: "https://corner-stats.com/fk-austria-vienna/austria/team/1627"},
 { team_name: "Rapid Wien", league: "austria_bundesliga", friendly_name: "rapid_wien", url: "https://corner-stats.com/rapid-vienna/austria/team/1573"},
 { team_name: "LASK Linz", league: "austria_bundesliga", friendly_name: "lask_linz", url: "https://corner-stats.com/lask-linz/austria/team/2193" },
 { team_name: "Red Bull Salzburg", league: "austria_bundesliga", friendly_name: "red_bull_salzburg", url: "https://corner-stats.com/fc-salzburg/austria/team/1704" },
 { team_name: "Rheindorf Altach", league: "austria_bundesliga", friendly_name: "rheindorf_altach", url: "https://corner-stats.com/scr-altach/austria/team/2387" },
 { team_name: "St. Polten", league: "austria_bundesliga", friendly_name: "st_polten", url: "https://corner-stats.com/st-polten/austria/team/2400" },
 { team_name: "Sturm Graz", league: "austria_bundesliga", friendly_name: "sturm_graz", url: "https://corner-stats.com/sk-sturm-graz/austria/team/2042" },
 { team_name: "SV Mattersburg", league: "austria_bundesliga", friendly_name: "sv_mattersburg", url: "https://corner-stats.com/sv-mattersburg/austria/team/2401" },
 { team_name: "Wolfsberger AC", league: "austria_bundesliga", friendly_name: "wolfsberger_ac", url: "https://corner-stats.com/wolfsberger-ac/austria/team/1890" }
],
austria_liga: [
 { team_name: "FAC Team fur Wien", search_name: 'FAC Team fur Wien', league: "Austria Erste Liga", friendly_name: "fac_team_fur_wien", url: "https://corner-stats.com/fac-team-fur-wien/austria/team/2397", id: '4350'},
 { team_name: "SV Ried", search_name: 'SV Ried', league: "Austria Erste Liga", friendly_name: "sv_ried", url: "https://corner-stats.com/sv-ried/austria/team/2389", id: '1048' },
 { team_name: "FC Blau-Weiß Linz", search_name: 'FC Blau Weiss Linz', league: "Austria Erste Liga", friendly_name: "fc_blau_weiß_linz", url: "https://corner-stats.com/blau-weis-linz/austria/team/451", id: '5801'},
 { team_name: "FC Liefering", search_name: 'FC Liefering', league: "Austria Erste Liga", friendly_name: "fc_liefering", url: "https://corner-stats.com/fc-liefering/austria/team/2395", id: '16583'},
 { team_name: "FC Wacker Innsbruck", search_name: 'FC Wacker Innsbruck', league: "Austria Erste Liga", friendly_name: "fc_wacker_innsbruck", url: "https://corner-stats.com/fc-wacker-innsbruck/austria/team/1963", id: '625' },
 { team_name: "SV Kapfenberg", search_name: 'SV Kapfenberg', league: "Austria Erste Liga", friendly_name: "sv_kapfenberg", url: "https://corner-stats.com/sv-kapfenberg/austria/team/2396", id: '528' },
 { team_name: "Austria Lustenau", search_name: 'Austria Lustenau', league: "Austria Erste Liga", friendly_name: "austria_lustenau", url: "https://corner-stats.com/austria-lustenau/austria/team/2399", id: '162' },
 { team_name: "Wiener Neustadt", search_name: 'Wiener Neustadt', league: "Austria Erste Liga", friendly_name: "wiener_neustadt", url: "https://corner-stats.com/wiener-neustadt/austria/team/2388", id: '8512' },
 { team_name: "TSV Hartberg", search_name: 'Hartberg', league: "Austria Erste Liga", friendly_name: "tsv_hartberg", url: "https://corner-stats.com/hartberg/austria/team/1970", id: '158' },
 { team_name: "WSG Swarovski Wattens", search_name: 'WSG Swarovski Wattens', league: "Austria Erste Liga", friendly_name: "wsg_swarovski_wattens", url: "https://corner-stats.com/swarovski-watt/austria/team/3870", id: '18616' }
],
china_super_league: [
 { team_name: "Beijing Guoan", league: "china_super_league", friendly_name: "beijing_guoan", url: "https://corner-stats.com/beijing-guoan/china-pr/team/1479"},
 { team_name: "Beijin Renhe", league: "china_super_league", friendly_name: "beijing_renhe", url: "https://corner-stats.com/guizhou-renhe/china-pr/team/1477" },
 { team_name: "Chongqing Lifan", league: "china_super_league", friendly_name: "chongqing_lifan", url: "https://corner-stats.com/chongqing-lifan/china-pr/team/2498" },
 { team_name: "Changchun Yatai", league: "china_super_league", friendly_name: "changchun_yatai", url: "https://corner-stats.com/changchun-yatai/china-pr/team/1850" },
 { team_name: "Dalian Yifang", league: "china_super_league", friendly_name: "dalian_yifang", url: "https://corner-stats.com/dalian-aerbin/china-pr/team/2808" },
 { team_name: "Guangzhou Evergrande", league: "china_super_league", friendly_name: "guangzhou_evergrande", url: "https://corner-stats.com/guangzhou-evergrande/china-pr/team/1476" },
 { team_name: "Guangzhou R & F", league: "china_super_league", friendly_name: "guangzhou_r_and_f", url: "https://corner-stats.com/guangzhou-rf/china-pr/team/1862" },
 { team_name: "Guizhou Zhicheng", league: "china_super_league", friendly_name: "guizhou_zhicheng", url: "https://corner-stats.com/guizhou-zhichen/china-pr/team/3989" },
 { team_name: "Hebei CFFC", league: "china_super_league", friendly_name: "hebei_cffc", url: "https://corner-stats.com/hebei-china-f/china-pr/team/4219" },
 { team_name: "Henan Jianye", league: "china_super_league", friendly_name: "henan_jianye", url: "https://corner-stats.com/henan-jianye/china-pr/team/2499" },
 { team_name: "Jiangsu Suning", league: "china_super_league", friendly_name: "jiangsu_suning", url: "https://corner-stats.com/jiangsu-sainty-fc/china-pr/team/1478" },
 { team_name: "Shanghai SIPG", league: "china_super_league", friendly_name: "shanghai_sipg", url: "https://corner-stats.com/shanghai-east-asia/china-pr/team/1750"},
 { team_name: "Shanghai Shenua", league: "china_super_league", friendly_name: "shanghai_shenua", url: "https://corner-stats.com/shanghai-shenhua/china-pr/team/1744"},
 { team_name: "Shandong Luneng", league: "china_super_league", friendly_name: "shandong_luneng", url: "https://corner-stats.com/shandong-luneng/china-pr/team/1740" },
 { team_name: "Tianjin Quanjian", league: "china_super_league", friendly_name: "tianjin_quanjian", url: "https://corner-stats.com/tianjin-song/china-pr/team/3971" },
 { team_name: "Tianjin Teda", league: "china_super_league", friendly_name: "tianjin_teda", url: "https://corner-stats.com/tianjin-teda/china-pr/team/1851" }
],
argentina_superliga: [
 { team_name: "Argentinos Juniors", league: "argentina_superliga", friendly_name: "argentinos_juniors", url: "https://corner-stats.com/argentinos-jrs/argentina/team/2144" },
 { team_name: "Atletico Tucuman", league: "argentina_superliga", friendly_name: "atletico_tucaman", url: "https://corner-stats.com/ca-tucuman/argentina/team/3248" },
 { team_name: "Arsenal (Arg)", league: "argentina_superliga", friendly_name: "arsenal_arg", url: "https://corner-stats.com/arsenal-de-sarandi/argentina/team/2347" },
 { team_name: "Banfield", league: "argentina_superliga", friendly_name: "banfield", url: "https://corner-stats.com/banfield/argentina/team/2343" },
 { team_name: "Belgrano", league: "argentina_superliga", friendly_name: "belgrano", url: "https://corner-stats.com/belgrano/argentina/team/2273" },
 { team_name: "Boca Juniors", league: "argentina_superliga", friendly_name: "boca_juniors", url: "https://corner-stats.com/boca-juniors/argentina/team/2272"},
 { team_name: "Chacarita Juniors", league: "argentina_superliga", friendly_name: "chacarita_juniors", url: "https://corner-stats.com/chacarita-jun/argentina/team/2145" },
 { team_name: "Colon", league: "argentina_superliga", friendly_name: "colon", url: "https://corner-stats.com/colon/argentina/team/2209"},
 { team_name: "Defensa Y Justica", league: "argentina_superliga", friendly_name: "defensa_y_justica", url: "https://corner-stats.com/defensa-y-justicia/argentina/team/2286" },
 { team_name: "Estudiantes", league: "argentina_superliga", friendly_name: "estudiantes", url: "https://corner-stats.com/estudiantes-lp/argentina/team/1835"},
 { team_name: "Gimnasia La Plata", league: "argentina_superliga", friendly_name: "gimnasia_la_plata", url: "https://corner-stats.com/gimnasia-lp/argentina/team/2345" },
 { team_name: "Godoy Cruz", league: "argentina_superliga", friendly_name: "godoy_cruz", url: "https://corner-stats.com/godoy-cruz/argentina/team/2346" },
 { team_name: "Huracan", league: "argentina_superliga", friendly_name: "huracan", url: "https://corner-stats.com/huracan/argentina/team/2284" },
 { team_name: "Independiente", league: "argentina_superliga", friendly_name: "independiente", url: "https://corner-stats.com/ca-independiente/argentina/team/2204" },
 { team_name: "Lanus", league: "argentina_superliga", friendly_name: "lanus", url: "https://corner-stats.com/lanus/argentina/team/1865"},
 { team_name: "Newells Old Boys", league: "argentina_superliga", friendly_name: "newells_old_boys", url: "https://corner-stats.com/newells/argentina/team/2203" },
 { team_name: "Olimpo", league: "argentina_superliga", friendly_name: "olimpo", url: "https://corner-stats.com/olimpo-b-blanca/argentina/team/2341" },
 { team_name: "Patronato", league: "argentina_superliga", friendly_name: "patronato", url: "https://corner-stats.com/patronato-parana/argentina/team/2730" },
 { team_name: "Racing Club", league: "argentina_superliga", friendly_name: "racing_club", url: "https://corner-stats.com/racing-club/argentina/team/2294" },
 { team_name: "River Plate", league: "argentina_superliga", friendly_name: "river_plate", url: "https://corner-stats.com/river-plate/argentina/team/2166" },
 { team_name: "Rosario Central", league: "argentina_superliga", friendly_name: "rosario_central", url: "https://corner-stats.com/rosario-central/argentina/team/2339" },
 { team_name: "San Lorenzo", league: "argentina_superliga", friendly_name: "san_lorenzo", url: "https://corner-stats.com/san-lorenzo/argentina/team/2138" },
 { team_name: "San Martin San Juan", league: "argentina_superliga", friendly_name: "san_martin", url: "https://corner-stats.com/san-martin-de-san-juan/argentina/team/2344" },
 { team_name: "Talleres Cordoba", league: "argentina_superliga", friendly_name: "talleres_cordoba", url: "https://corner-stats.com/talleres-cord/argentina/team/3650" },
 { team_name: "Temperley", league: "argentina_superliga", friendly_name: "temperley", url: "https://corner-stats.com/temperley/argentina/team/2271"},
 { team_name: "Tigre", league: "argentina_superliga", friendly_name: "tigre", url: "https://corner-stats.com/ca-tigre/argentina/team/2340" },
 { team_name: "Union Santa Fe", league: "argentina_superliga", friendly_name: "union_santa_fe", url: "https://corner-stats.com/union-santa-fe/argentina/team/2207" },
 { team_name: "Velez Sarsfield", league: "argentina_superliga", friendly_name: "velez_sarsfield", url: "https://corner-stats.com/velez-sarsfield/argentina/team/2348"}
],
roi_premier: [
 { team_name: "Bohemians", search_name: 'Bohemians Dublin', league: "Republic of Ireland Premier Division", friendly_name: "bohemians", url: "https://corner-stats.com/bohemians-dublin/ireland-republic/team/699", id: '7274'},
 { team_name: "Bray", search_name: 'Bray Wanderers', league: "Republic of Ireland Premier Division", friendly_name: "bray", url: "https://corner-stats.com/bray-wanderers/ireland-republic/team/2689", id: '241'},
 { team_name: "Cork City", search_name: 'Cork City', league: "Republic of Ireland Premier Division", friendly_name: "cork_city", url: "https://corner-stats.com/cork-city/ireland-republic/team/2691", id: '243' },
 { team_name: "Derry City", search_name: 'Derry City', league: "Republic of Ireland Premier Division", friendly_name: "derry_city", url: "https://corner-stats.com/derry-city/northern-ireland/team/2698", id: '248' },
 { team_name: "Dundalk", search_name: 'Dundalk', league: "Republic of Ireland Premier Division", friendly_name: "dundalk", url: "https://corner-stats.com/dundalk/ireland-republic/team/2695", id: '245' },
 { team_name: "Limerick", search_name: 'Limerick', league: "Republic of Ireland Premier Division", friendly_name: "limerick", url: "https://corner-stats.com/limerick/ireland-republic/team/291", id: '254' },
 { team_name: "Shamrock", search_name: 'Shamrock Rovers', league: "Republic of Ireland Premier Division", friendly_name: "shamrock", url: "https://corner-stats.com/shamrock-rovers/ireland-republic/team/1821", id: '236'},
 { team_name: "Sligo Rovers", search_name: 'Sligo Rovers', league: "Republic of Ireland Premier Division", friendly_name: "sligo_rovers", url: "https://corner-stats.com/sligo-rovers/ireland-republic/team/987", id: '246' },
 { team_name: "St Patricks", search_name: 'St Patricks', league: "Republic of Ireland Premier Division", friendly_name: "st_patricks", url: "https://corner-stats.com/st-patricks/ireland-republic/team/459", id: '259' },
 { team_name: "Waterford", search_name: 'Waterford FC', league: "Republic of Ireland Premier Division", friendly_name: "waterford", url: "https://corner-stats.com/waterford-utd/ireland-republic/team/3029", id: '41325' }
]
}
